# Generated by Django 4.2.3 on 2023-12-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(db_index=True, verbose_name='Visited at')),
                ('link', models.URLField(verbose_name='Visited link')),
                ('domain', models.URLField(verbose_name='Visited domain')),
            ],
        ),
    ]
